name: topfive
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics: ^4.0.4
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  firebase_storage: ^12.1.3
  firebase_database: ^11.0.4
  firebase_core: ^3.3.0 # Update this to the latest version
  image_picker: ^0.8.7+5
  google_fonts: ^6.2.0
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  assets:
    - assets/AuthKey_YSLY5MFAZ2.p8
  uses-material-design: true